### ISSUE TITLE
AttributeError: module 'gorilla' has no attribute 'track'

### ISSUE THREAD

**Issue by Bostoncake** [Gorilla-Lab-SCUT/TTAC#1]
When preparing the ImageNet data as instructed by the readme.md inside the `imagenet/` folder, I receive the error `AttributeError: module 'gorilla' has no attribute 'track'`. I downloaded the `gorilla==0.4.0` package from https://github.com/christophercrouzet/gorilla and it seems that it doesn't have an attribute named `track`. Would you please provide the `gorilla` package you are using? Thanks!

**Comment by Dyb3438** [comment]
The `gorilla` package is here: https://github.com/Gorilla-Lab-SCUT/gorilla-core.
You should install it by `pip install gorilla-core`.

**Comment by Bostoncake** [comment]
It worked! Thanks!
