### ISSUE TITLE
The download link of pre-trained model return a 404 error

### ISSUE THREAD

**Issue by ynanwu** [Gorilla-Lab-SCUT/TTAC#4]
Could you please provide the download link for the pre-trained ResNet50 again? The following two download links return a 404 error. Thanks.

“mkdir -p results/cifar10_joint_resnet50 && cd results/cifar10_joint_resnet50
gdown https://drive.google.com/uc?id=1TWiFJY_q5uKvNr9x3Z4CiK2w9Giqk9Dx && cd ../..
mkdir -p results/cifar100_joint_resnet50 && cd results/cifar100_joint_resnet50
gdown https://drive.google.com/uc?id=1-8KNUXXVzJIPvao-GxMp2DiArYU9NBRs && cd ../..”

**Comment by Dyb3438** [comment]
Sure, I have uploaded the pretrained checkpoints at https://drive.google.com/drive/folders/1KJIhoB_Iz1OvmpWyUqSIICdafYpo9Dih?usp=sharing
